version: '3'


services:
  web:
    build: .
    command: bash -c "python restaurant/manage.py migrate && python restaurant/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"